// 模块: YuEngine World
// 文件: Src/YuEngine/World/Include/YuEngine/World/WorldSceneAssemblyManifestStreamConstants.h

#pragma once

#include <cstdint>

#include "YuEngine/Serialize/SerializeConstants.h"
#include "YuEngine/Serialize/SerializeFieldId.h"
#include "YuEngine/Serialize/SerializeRecordId.h"
#include "YuEngine/World/WorldConstants.h"

namespace yuengine::world {
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_STREAM_SCHEMA_VERSION = 1U;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_RECORD_BYTE_COUNT = 12U;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_RECORD_BYTE_COUNT = 24U;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_RECORD_CAPACITY = 16U;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_RECORD_CAPACITY = 10U;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_MAX_CHUNK_RECORD_COUNT =
    (MAX_WORLD_OBJECT_COUNT + WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_RECORD_CAPACITY - 1U) /
    WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_MAX_CHUNK_RECORD_COUNT =
    (MAX_WORLD_OBJECT_COUNT + WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_RECORD_CAPACITY - 1U) /
    WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_PAYLOAD_BYTE_COUNT =
    WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_RECORD_BYTE_COUNT *
    WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_PAYLOAD_BYTE_COUNT =
    WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_RECORD_BYTE_COUNT *
    WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_METADATA_FIELD_COUNT = 5U;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_UINT32_FIELD_BYTE_COUNT =
    yuengine::serialize::FIELD_HEADER_BYTE_COUNT + yuengine::serialize::UINT32_PAYLOAD_BYTE_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT =
    yuengine::serialize::FIELD_HEADER_BYTE_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_METADATA_RECORD_BYTE_COUNT =
    yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
    (WORLD_SCENE_ASSEMBLY_MANIFEST_METADATA_FIELD_COUNT *
        WORLD_SCENE_ASSEMBLY_MANIFEST_UINT32_FIELD_BYTE_COUNT);
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_MAX_RECORD_COUNT =
    1U +
    WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_MAX_CHUNK_RECORD_COUNT +
    WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_MAX_CHUNK_RECORD_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_MAX_FIELD_COUNT =
    WORLD_SCENE_ASSEMBLY_MANIFEST_METADATA_FIELD_COUNT +
    WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_MAX_CHUNK_RECORD_COUNT +
    WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_MAX_CHUNK_RECORD_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_MAX_WRITE_BYTE_COUNT =
    WORLD_SCENE_ASSEMBLY_MANIFEST_METADATA_RECORD_BYTE_COUNT +
    (WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_MAX_CHUNK_RECORD_COUNT *
        (yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
            WORLD_SCENE_ASSEMBLY_MANIFEST_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT +
            WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_PAYLOAD_BYTE_COUNT)) +
    (WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_MAX_CHUNK_RECORD_COUNT *
        (yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
            WORLD_SCENE_ASSEMBLY_MANIFEST_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT +
            WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_PAYLOAD_BYTE_COUNT));

inline constexpr yuengine::serialize::SerializeRecordId
    WORLD_SCENE_ASSEMBLY_MANIFEST_METADATA_RECORD_ID{500U};
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_RECORD_ID_BASE = 501U;
inline constexpr std::uint32_t WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_RECORD_ID_BASE = 520U;

inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_ASSEMBLY_MANIFEST_FIELD_SCHEMA_VERSION{1U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_ASSEMBLY_MANIFEST_FIELD_ATTACHMENT_RECORD_COUNT{2U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_ASSEMBLY_MANIFEST_FIELD_BINDING_RECORD_COUNT{3U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_ASSEMBLY_MANIFEST_FIELD_ATTACHMENT_CHUNK_COUNT{4U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_ASSEMBLY_MANIFEST_FIELD_BINDING_CHUNK_COUNT{5U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_ASSEMBLY_MANIFEST_CHUNK_FIELD_RECORD_BYTES{1U};

static_assert(
    WORLD_SCENE_ASSEMBLY_MANIFEST_ATTACHMENT_CHUNK_PAYLOAD_BYTE_COUNT <=
    yuengine::serialize::MAX_FIELD_PAYLOAD_BYTE_COUNT);
static_assert(
    WORLD_SCENE_ASSEMBLY_MANIFEST_BINDING_CHUNK_PAYLOAD_BYTE_COUNT <=
    yuengine::serialize::MAX_FIELD_PAYLOAD_BYTE_COUNT);
static_assert(
    WORLD_SCENE_ASSEMBLY_MANIFEST_MAX_RECORD_COUNT <=
    yuengine::serialize::MAX_RECORDS_PER_STREAM);
static_assert(
    WORLD_SCENE_ASSEMBLY_MANIFEST_MAX_FIELD_COUNT <=
    yuengine::serialize::MAX_FIELDS_PER_STREAM);
static_assert(
    WORLD_SCENE_ASSEMBLY_MANIFEST_MAX_WRITE_BYTE_COUNT +
    yuengine::serialize::STREAM_HEADER_BYTE_COUNT <=
    yuengine::serialize::MAX_STREAM_BYTE_COUNT);
}
