// 模块: YuEngine World
// 文件: Src/YuEngine/World/Include/YuEngine/World/WorldComponentResourceBindingSnapshotConstants.h

#pragma once

#include <cstdint>

#include "YuEngine/Serialize/SerializeConstants.h"
#include "YuEngine/Serialize/SerializeFieldId.h"
#include "YuEngine/Serialize/SerializeRecordId.h"
#include "YuEngine/World/WorldConstants.h"

namespace yuengine::world {
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_SCHEMA_VERSION = 1U;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_RECORD_BYTE_COUNT = 24U;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_RECORD_CAPACITY = 10U;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_MAX_CHUNK_RECORD_COUNT =
    (MAX_WORLD_OBJECT_COUNT + WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_RECORD_CAPACITY - 1U) /
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_PAYLOAD_BYTE_COUNT =
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_RECORD_BYTE_COUNT *
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_METADATA_FIELD_COUNT = 3U;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_UINT32_FIELD_BYTE_COUNT =
    yuengine::serialize::FIELD_HEADER_BYTE_COUNT + yuengine::serialize::UINT32_PAYLOAD_BYTE_COUNT;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT =
    yuengine::serialize::FIELD_HEADER_BYTE_COUNT;
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_METADATA_RECORD_BYTE_COUNT =
    yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
    (WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_METADATA_FIELD_COUNT *
        WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_UINT32_FIELD_BYTE_COUNT);

inline constexpr yuengine::serialize::SerializeRecordId
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_METADATA_RECORD_ID{400U};
inline constexpr std::uint32_t WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_RECORD_ID_BASE = 401U;

inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_FIELD_SCHEMA_VERSION{1U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_FIELD_RECORD_COUNT{2U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_FIELD_CHUNK_COUNT{3U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_FIELD_RECORD_BYTES{1U};

static_assert(
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_CHUNK_PAYLOAD_BYTE_COUNT <=
    yuengine::serialize::MAX_FIELD_PAYLOAD_BYTE_COUNT);
static_assert(
    WORLD_COMPONENT_RESOURCE_BINDING_SNAPSHOT_MAX_CHUNK_RECORD_COUNT + 1U <=
    yuengine::serialize::MAX_RECORDS_PER_STREAM);
}
