// Module: YuEngine World
// File: Src/YuEngine/World/Include/YuEngine/World/WorldSceneObjectTransformManifestStreamConstants.h

#pragma once

#include <cstdint>

#include "YuEngine/Serialize/SerializeConstants.h"
#include "YuEngine/Serialize/SerializeFieldId.h"
#include "YuEngine/Serialize/SerializeRecordId.h"
#include "YuEngine/World/WorldConstants.h"

namespace yuengine::world {
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_STREAM_SCHEMA_VERSION = 1U;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_RECORD_BYTE_COUNT = 12U;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_RECORD_BYTE_COUNT = 44U;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_RECORD_CAPACITY = 16U;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_RECORD_CAPACITY = 5U;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_MAX_CHUNK_RECORD_COUNT =
    (MAX_WORLD_OBJECT_COUNT +
        WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_RECORD_CAPACITY - 1U) /
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_MAX_CHUNK_RECORD_COUNT =
    (MAX_WORLD_OBJECT_COUNT +
        WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_RECORD_CAPACITY - 1U) /
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_PAYLOAD_BYTE_COUNT =
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_RECORD_BYTE_COUNT *
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_PAYLOAD_BYTE_COUNT =
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_RECORD_BYTE_COUNT *
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_RECORD_CAPACITY;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_METADATA_FIELD_COUNT = 5U;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_UINT32_FIELD_BYTE_COUNT =
    yuengine::serialize::FIELD_HEADER_BYTE_COUNT +
    yuengine::serialize::UINT32_PAYLOAD_BYTE_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT =
    yuengine::serialize::FIELD_HEADER_BYTE_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_METADATA_RECORD_BYTE_COUNT =
    yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
    (WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_METADATA_FIELD_COUNT *
        WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_UINT32_FIELD_BYTE_COUNT);
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_RECORD_COUNT =
    1U +
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_MAX_CHUNK_RECORD_COUNT +
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_MAX_CHUNK_RECORD_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_FIELD_COUNT =
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_METADATA_FIELD_COUNT +
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_MAX_CHUNK_RECORD_COUNT +
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_MAX_CHUNK_RECORD_COUNT;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_TRANSFORM_REMAINDER_COUNT =
    MAX_WORLD_OBJECT_COUNT -
    ((WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_MAX_CHUNK_RECORD_COUNT - 1U) *
        WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_RECORD_CAPACITY);
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_WRITE_BYTE_COUNT =
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_METADATA_RECORD_BYTE_COUNT +
    (WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_MAX_CHUNK_RECORD_COUNT *
        (yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
            WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT +
            WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_PAYLOAD_BYTE_COUNT)) +
    ((WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_MAX_CHUNK_RECORD_COUNT - 1U) *
        (yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
            WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT +
            WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_PAYLOAD_BYTE_COUNT)) +
    (yuengine::serialize::RECORD_HEADER_BYTE_COUNT +
        WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIXED_BYTES_FIELD_HEADER_BYTE_COUNT +
        (WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_TRANSFORM_REMAINDER_COUNT *
            WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_RECORD_BYTE_COUNT));

inline constexpr yuengine::serialize::SerializeRecordId
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_METADATA_RECORD_ID{700U};
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_RECORD_ID_BASE = 701U;
inline constexpr std::uint32_t WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_RECORD_ID_BASE = 720U;

inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIELD_SCHEMA_VERSION{1U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIELD_IDENTITY_RECORD_COUNT{2U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIELD_TRANSFORM_RECORD_COUNT{3U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIELD_IDENTITY_CHUNK_COUNT{4U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_FIELD_TRANSFORM_CHUNK_COUNT{5U};
inline constexpr yuengine::serialize::SerializeFieldId
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_CHUNK_FIELD_RECORD_BYTES{1U};

static_assert(sizeof(float) == sizeof(std::uint32_t));
static_assert(
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_IDENTITY_CHUNK_PAYLOAD_BYTE_COUNT <=
    yuengine::serialize::MAX_FIELD_PAYLOAD_BYTE_COUNT);
static_assert(
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_TRANSFORM_CHUNK_PAYLOAD_BYTE_COUNT <=
    yuengine::serialize::MAX_FIELD_PAYLOAD_BYTE_COUNT);
static_assert(
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_RECORD_COUNT <=
    yuengine::serialize::MAX_RECORDS_PER_STREAM);
static_assert(
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_FIELD_COUNT <=
    yuengine::serialize::MAX_FIELDS_PER_STREAM);
static_assert(
    WORLD_SCENE_OBJECT_TRANSFORM_MANIFEST_MAX_WRITE_BYTE_COUNT +
    yuengine::serialize::STREAM_HEADER_BYTE_COUNT <=
    yuengine::serialize::MAX_STREAM_BYTE_COUNT);
}
