#!/usr/bin/env python3
"""
Generate an engine API surface map from native boundary spec inputs.

The output groups script-visible API obligations by engine service. It is a design/tracking map,
not a runtime implementation claim.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    from native_spec import build_spec
    from sqir import default_db_path
except ImportError:  # pragma: no cover
    from tools.native_spec import build_spec
    from tools.sqir import default_db_path


SERVICE_MODULES = {
    "Actor And Task Service": "engine/actor_task",
    "Audio Service": "engine/audio",
    "Camera Service": "engine/camera",
    "Collision And Physics-Lite Service": "engine/collision",
    "Event/Quest/Flag Service": "engine/event_quest_flag",
    "Platform Service": "engine/platform",
    "Resource Service": "engine/resource",
    "Save/Profile/Scenario Service": "engine/save_profile_scenario",
    "Scene And Stage Service": "engine/scene_stage",
    "Script Service": "engine/script",
    "UI And 2D Render Service": "engine/ui_render_2d",
}


def build_surface(scripts: list[Path], db_path: Path | None) -> dict[str, Any]:
    spec = build_spec(scripts, db_path)
    services: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in spec["rows"]:
        services[row["service_owner"]].append(row)

    service_rows = []
    for service, rows in sorted(services.items()):
        total_call_sites = sum(row["call_sites"] for row in rows)
        service_rows.append(
            {
                "service": service,
                "module": SERVICE_MODULES.get(service, "engine/unassigned"),
                "api_count": len(rows),
                "call_sites": total_call_sites,
                "apis": sorted(rows, key=lambda row: row["name"]),
                "implementation_status": "not_started",
                "evidence_level": "E1",
                "notes": [
                    "surface is generated from script boundary evidence",
                    "argument/return/side effects remain unknown until P4/P1/P2 evidence improves",
                ],
            }
        )

    return {
        "format": "yuengine.api_surface.v1",
        "scope": spec["scope"],
        "source_scripts": spec["source_scripts"],
        "summary": {
            "service_count": len(service_rows),
            "api_count": spec["summary"]["boundary_count"],
            "call_sites": spec["summary"]["call_sites"],
            "unassigned": spec["summary"]["unassigned"],
        },
        "services": service_rows,
    }


def write_markdown(path: Path, surface: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    summary = surface["summary"]
    lines = [
        "# Engine API Surface: Title/New-Game/First-Mission",
        "",
        "Generated by `tools/api_surface.py` from Script IR and native boundary spec rules.",
        "",
        "This maps script-visible API obligations to engine services. It does not implement or",
        "confirm native behavior.",
        "",
        "## Summary",
        "",
        f"- Services: {summary['service_count']}",
        f"- APIs: {summary['api_count']}",
        f"- Call sites: {summary['call_sites']}",
        f"- Unassigned: {len(summary['unassigned'])}",
        "",
        "## Source Scripts",
        "",
    ]
    lines.extend(f"- `{script['sqasm_path']}`" for script in surface["source_scripts"])
    lines.extend(["", "## Services", ""])

    for service in surface["services"]:
        lines.extend(
            [
                f"### {service['service']}",
                "",
                f"- Proposed module: `{service['module']}`",
                f"- APIs: {service['api_count']}",
                f"- Call sites: {service['call_sites']}",
                f"- Implementation status: `{service['implementation_status']}`",
                "",
                "| API | Calls | Owner Level | Evidence | Status |",
                "| --- | ---: | --- | --- | --- |",
            ]
        )
        for api in service["apis"]:
            lines.append(
                f"| `{api['name']}` | {api['call_sites']} | {api['owner_level']} | "
                f"{api['evidence_level']} | {api['implementation_status']} |"
            )
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def write_json(path: Path, surface: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(surface, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--script", action="append", type=Path, required=True)
    parser.add_argument("--db", type=Path, default=default_db_path())
    parser.add_argument("--no-db", action="store_true")
    parser.add_argument("--json-out", type=Path)
    parser.add_argument("--md-out", type=Path)
    parser.add_argument("--stdout", action="store_true")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    for script in args.script:
        if not script.exists():
            parser.error(f"script not found: {script}")
    surface = build_surface(args.script, None if args.no_db else args.db)
    if args.json_out:
        write_json(args.json_out, surface)
    if args.md_out:
        write_markdown(args.md_out, surface)
    if args.stdout or not (args.json_out or args.md_out):
        print(json.dumps(surface, indent=2, ensure_ascii=False))
    else:
        print(
            "api-surface: "
            f"{surface['summary']['service_count']} services, "
            f"{surface['summary']['api_count']} APIs, "
            f"{surface['summary']['call_sites']} call sites"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
